// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymodflxaqfapokvsdivd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltb2RmbHhhcWZhcG9rdnNkaXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDcxMzQsImV4cCI6MjA2MDkyMzEzNH0.fjkUm37ZZ1eQ3FFo9E2ysW87ouD-xv1xxEFPnPrBy6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);